// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhiwbykovleijmthuhei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oaXdieWtvdmxlaWptdGh1aGVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjkzNDYsImV4cCI6MjA2OTU0NTM0Nn0.dVyJ1d8EnwqbtSEDxRo6l_bwIWr29NKPvoEWEdhwcvc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});